module;

#include <string_view>

export module example;

export namespace example {
const std::string_view example =
    R"(............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............)";
}